### ISSUE TITLE
Cant detect Web Crypto API

### ISSUE THREAD

**Issue by monomy001** [tiagosiebler/bybit-api#496]
I'm using nodejs msi installer on windows, been using on other projects no problem.
I try this bybit-api, after installing i got this message

throw new Error(`Web Crypto API unavailable. Authentication will not work.
        ^

Error: Web Crypto API unavailable. Authentication will not work.

Are you using an old Node.js release? Refer to the current Node.js LTS version. Node.js v18 reached end of life in April 2025! You should be using Node LTS or newer (v22 or above)!

I was already using v22.xx. I thought maybe I need to use the latest version. So I reinstalled, now Node.js v24.10.0
yet i still see such error message when i try to run

at checkWebCryptoAPISupported (\node_modules\bybit-api\lib\util\webCryptoAPI.js:110:15)
    at new BaseRestClient (\node_modules\bybit-api\lib\util\BaseRestClient.js:93:59)
    at new RestClientV5 (\node_modules\bybit-api\lib\rest-client-v5.js:23:1)

can anyone help? this is already the latest nodejs version. what should i do?

**Comment by tiagosiebler** [comment]
Curious, is this purely Node.js / backend? If you run `node --version`, what does it give you? My immediate thought is you might have multiple node versions installed by accident and it's using the older one.

**Comment by monomy001** [comment]
backend actually.. i use const { RestClientV5 } = require('bybit-api'); 
D:\_Documents\_server>node --version
v24.10.0

I made sure theres no other nodejs installation apart from this one. (already clean remove programs for the v22)

Here's the full list of error message, not sure if it will help
D:\_Documents\_server\node_modules\bybit-api\lib\util\webCryptoAPI.js:110
        throw new Error(`Web Crypto API unavailable. Authentication will not work.
        ^

Error: Web Crypto API unavailable. Authentication will not work.

Are you using an old Node.js release? Refer to the current Node.js LTS version. Node.js v18 reached end of life in April 2025! You should be using Node LTS or newer (v22 or above)!

If you prefer to continue using an outdated Node.js version, check github for an example on using the node:crypto module for sign instead:
https://github.com/tiagosiebler/bybit-api/blob/master/examples/fasterHmacSign.ts

    at checkWebCryptoAPISupported (D:\_Documents\_server\node_modules\bybit-api\lib\util\webCryptoAPI.js:110:15)
    at new BaseRestClient (D:\_Documents\_server\node_modules\bybit-api\lib\util\BaseRestClient.js:93:59)
    at new RestClientV5 (D:\_Documents\_server\node_modules\bybit-api\lib\rest-client-v5.js:23:1)
    at setupArbitrage2 (D:\_Documents\_server\monomy\route-arbitrage.js:431:20)
    at Object.<anonymous> (D:\_Documents\_server\monomy\route-arbitrage.js:452:1)
    at Module._compile (node:internal/modules/cjs/loader:1760:14)
    at Object..js (node:internal/modules/cjs/loader:1893:10)
    at Module.load (node:internal/modules/cjs/loader:1480:32)
    at Module._load (node:internal/modules/cjs/loader:1299:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)

Node.js v24.10.0

**Comment by monomy001** [comment]
FYI this also happens with the binance sdk that you develop.
Heres an advance question.. is it possible to reuse this one repo to also controls binance etc other exchanges API? coz i think they are pretty much the same right? just difference in url endpoint & its properties. i want to avoid installing too many separate plugins if functionality is similar

**Comment by tiagosiebler** [comment]
Strange to see this. I've switched to v24.10.0 using nvm, albeit on Mac, and no issues here. Quick check also shows all are present, although out of curiosity I included some overkill checks too:
```

async function checkWebCryptoAPI() {
  console.log(
    'globalThis: ',
    globalThis.crypto,
    globalThis.crypto?.subtle,
    globalThis.crypto?.subtle?.sign,
    globalThis.crypto?.subtle?.importKey,
  );
  console.log(
    'this: ',
    this.crypto,
    this.crypto?.subtle,
    this.crypto?.subtle?.sign,
    this.crypto?.subtle?.importKey,
  );
  console.log(
    'global: ',
    global.crypto,
    global.crypto?.subtle,
    global.crypto?.subtle?.sign,
    global.crypto?.subtle?.importKey,
  );
  console.log(
    '.: ',
    crypto,
    crypto?.subtle,
    crypto?.subtle?.sign,
    crypto?.subtle?.importKey,
  );
}
checkWebCryptoAPI();
```

```
globalThis:  Crypto {} SubtleCrypto {} [AsyncFunction: sign] [AsyncFunction: importKey]
this:  Crypto {} SubtleCrypto {} [AsyncFunction: sign] [AsyncFunction: importKey]
global:  Crypto {} SubtleCrypto {} [AsyncFunction: sign] [AsyncFunction: importKey]
.:  Crypto {} SubtleCrypto {} [AsyncFunction: sign] [AsyncFunction: importKey]
```

All of them are defined (although globalThis is typically universally safer).

Accessing SubtleCrypto via globalThis.crypto is standard practice that's formally documented, with wide compatibility in the ecosystem (or I wouldn't have switched to it):
https://nodejs.org/api/webcrypto.html#sign-and-verify

Could you run the above snippet too and share the console output you see for each line? Curious if this is any different for you.

**Comment by tiagosiebler** [comment]
> FYI this also happens with the binance sdk that you develop. Heres an advance question.. is it possible to reuse this one repo to also controls binance etc other exchanges API? coz i think they are pretty much the same right? just difference in url endpoint & its properties. i want to avoid installing too many separate plugins if functionality is similar

Each exchange is unfortunately quite different. Each exchange has different rules for how the request signature (authentication) should be prepared, how the request should be built and structured, and everything in between. That's why we spent quite a lot of time making SDKs for each of the exchanges we work with. Even more so if you're using WebSockets at all. So if you're looking to use the Binance APIs too, you will need to install the binance npm package as well and use that for all Binance related API calls.

**Comment by monomy001** [comment]
> Strange to see this. I've switched to v24.10.0 using nvm, albeit on Mac, and no issues here. Quick check also shows all are present, although out of curiosity I included some overkill checks too:
> Could you run the above snippet too and share the console output you see for each line? Curious if this is any different for you.

<img width="918" height="389" alt="Image" src="https://github.com/user-attachments/assets/0cac4707-72a0-494f-b619-0b8761217d1f" />
Nope.. the test snippet results is the same.. yet i still got web crypto API unavailable..
I'm trying to connect at least 6 crypto marketplaces.. looks like if i just use websocket, i'll be reinventing your wheels yea..

so any other ideas/solution how to overcome this web crypto API not available? 
(I did mention this is backend right? ie: not front end react javascript)

**Comment by tiagosiebler** [comment]
This is useful, thanks for the logs. So it's definitely available but perhaps my "falsy" detection mechanic is too lax. I'll add a strict undefined guard instead and then we can see if this fixes it. Will push a fix for you to test, shortly.

**Comment by monomy001** [comment]
OWH GAWD!! I'm so sorry.. my bad..
I found out the problem..

<img width="520" height="419" alt="Image" src="https://github.com/user-attachments/assets/297c3532-a0a4-4dc8-8259-fd70ac4bb197" />

I was trying the bare minimal example, just putting in key & secret.. i didnt put in customSignMessageFn (as the docs says need to see example fasterhmacsign or something..

this trips your validation on BaseRestClient > constructor
<img width="623" height="233" alt="Image" src="https://github.com/user-attachments/assets/d5755d30-b77a-4cdb-9f9c-1eea86e95a6a" />

I just add in that function, it works now..
I guess u should just put information on documentation to always put the customSignMessageFn even if its just an empty function.

I do however find another "problem"? lol, as u can see on the first screenshot, even when the crypto validation didnt trips, it says ETIMEDOUT for some reason?
how do i debug this? should i open another issue? or just continue on this thread?

**Comment by tiagosiebler** [comment]
The thing is, unless you're using an outdated node version as old as v18 (or older), this should work for you **without** using the injected custom sign function. Web Crypto API is generally available for everyone for some time now. I think the flaw is in how I was loosely detecting whether web crypto api is available. The logs in your previous screenshot tell me that it definitely is for you.

I've just published a beta with a fix. Can you try it out, without using the customSignMessageFn? `npm install bybit-api@beta` should fetch v4.4.1-beta.0 for you. Let me know if that fixes it, and then I'll release it properly. Thanks!

**Comment by monomy001** [comment]
<img width="907" height="334" alt="Image" src="https://github.com/user-attachments/assets/8bde21db-2fa2-499c-8caa-612f30ccadf1" />

nope, still the same.. bt i think u can ignore this.. 
i think i know what my problem is.. i have a constant declaration globalThis on my project..
i think it overrides checkWebCryptoAPISupported
this wont happen to other people.
i didnt know globalThis is a reserved variable names on nodejs

**Comment by monomy001** [comment]
<img width="419" height="108" alt="Image" src="https://github.com/user-attachments/assets/91ec3c38-9b7b-48e0-8e45-ad0362e5718a" />

yup, can confirm its just my specific issue.. after i change the constant declaration globalThis to globalThat, i dont get anymore errors. now just having timed out connection.
Thanks so much & apologies for the false alarm
